version: '3'

services:
 rails:
  build: ./blog
  ports:
   - "3000:3000"
  container_name: rails
  depends_on:
   - mysql

 mysql:
  image: mysql
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=Svirinandrew1234!     
  container_name: mysql
  command: --default-authentication-plugin=mysql_native_password
